galileo_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  shoulder_pan_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_lift_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ee_position_controller:
    type: position_controllers/JointPositionController
    joint: ee_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  #gripper_joint_1_position_controller:
    #type: position_controllers/JointPositionController
    #joint: gripper_joint_1
  #gripper_joint_2_position_controller:
    #type: position_controllers/JointPositionController
    #joint: gripper_joint_2

