arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [shoulder_pan_joint,shoulder_lift_joint,elbow_joint,wrist_joint,ee_joint]

gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [finger_joint]
    
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
