arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - elbow_joint 
     - shoulder_lift_joint 
     - shoulder_pan_joint 
     - wrist_joint 
     - ee_joint 
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - finger_joint
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
